# Generated by Django 5.2.4 on 2025-07-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_name_product_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Image',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
